name: Build and deploy Python project to Azure Function App - BinanceTradeBot

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.11'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      # Nainstalujeme závislosti do .python_packages (Azure Functions je umí načíst přímo z balíčku)
      - name: Install dependencies into .python_packages
        run: |
          pip install -r requirements.txt -t .python_packages/lib/site-packages

      # Zabalíme přesně kořenový obsah, který FunApp očekává
      - name: Create deployment zip
        run: |
          zip -r release.zip host.json requirements.txt .python_packages BinanceTradeBot

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_69E5CE2EDA7C4175BFCE5A3FBE71761F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B896266DBCF74093BD42E8A951B15627 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_6986CDF3F45C426181635AD63931D50E }}

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: 'BinanceTradeBot'        # přesný název tvé Function App
          slot-name: 'Production'
          package: 'release.zip'              # posíláme ZIP, ne adresář

